apiVersion: zscaler-zpa.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: zcaler-zpa-creds
      namespace: crossplane-system
      key: credentials
